name: 'Docker Build'

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  issues: write
  pull-requests: write
  contents: write

jobs:
  sementic-release:
    name: 'Docker Build'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Version
        run: echo ${{ steps.semantic.outputs.release-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: lsdtrip/tanzu-builder:${{ steps.semantic.outputs.release-version }}